(() => {
  'use strict';
  const API='https://app.ironqx.fit/api/commercial-chat',LEAD='https://app.ironqx.fit/api/commercial-lead';
  const PHONE='593963252197',EMAIL='ironqx.coach@gmail.com';
  const FALLBACK=[{id:'balance',name:'Balance',price:60,period:'mes',description:'Nutrición y entrenamiento personalizados, controles quincenales, sin sesiones presenciales 1 a 1.'},{id:'forged',name:'Forged',price:75,period:'mes',description:'Ajustes semanales y una sesión presencial 1 a 1 por semana.'},{id:'restore',name:'Restore',price:100,period:'mes',description:'Mayor supervisión médica y dos sesiones presenciales 1 a 1 por semana.'},{id:'consulta',name:'Consulta + InBody',price:30,period:'consulta',description:'Consulta médica puntual con InBody.'}];
  const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const icon=name=>window.lucide.createElement(window.lucide.icons[name],{'aria-hidden':'true','stroke-width':1.8});
  const host=el('div');host.id='ironqx-assistant';document.body.append(host);const root=host.attachShadow({mode:'open'});
  const css=document.createElement('link');css.rel='stylesheet';css.href='/assistant.css?v=2026100306';root.append(css);
  const backdrop=el('div','backdrop');backdrop.hidden=true;backdrop.setAttribute('aria-hidden','true');root.append(backdrop);
  const fab=el('button','fab');fab.type='button';fab.title='Conversar con IronQx Assistant';fab.setAttribute('aria-label',fab.title);fab.setAttribute('aria-expanded','false');fab.setAttribute('aria-controls','iqx-commercial-chat');fab.append(icon('MessageCircle'));root.append(fab);
  const panel=el('section','panel');panel.id='iqx-commercial-chat';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','IronQx Assistant');root.append(panel);
  const header=el('header','header'),logo=el('img','logo');logo.src='/images/app-logo.webp';logo.alt='IronQx';header.append(logo);
  const identity=el('div','identity');identity.append(el('strong',null,'IronQx Assistant'),el('span',null,'Dr. Daniel Arévalo'));header.append(identity);
  const reset=el('button','icon');reset.title='Empezar de nuevo';reset.setAttribute('aria-label',reset.title);reset.append(icon('RotateCcw'));header.append(reset);
  const close=el('button','icon');close.title='Cerrar chat';close.setAttribute('aria-label',close.title);close.append(icon('X'));header.append(close);panel.append(header);
  const timeline=el('div','timeline');timeline.setAttribute('role','log');timeline.setAttribute('aria-live','polite');timeline.setAttribute('aria-relevant','additions');panel.append(timeline);
  const requestView=el('div','request-view');requestView.hidden=true;panel.append(requestView);
  const composer=el('form','composer'),row=el('div','input-row'),input=el('textarea');input.rows=1;input.maxLength=1200;input.placeholder='Escribe tu mensaje…';input.setAttribute('aria-label','Tu mensaje');
  const send=el('button','send');send.type='submit';send.title='Enviar mensaje';send.setAttribute('aria-label',send.title);send.append(icon('Send'));row.append(input,send);composer.append(row);
  const bottom=el('div','bottom-actions'),human=el('a','text-action','Hablar con Daniel');human.href='https://wa.me/'+PHONE;human.target='_blank';human.rel='noopener noreferrer';human.prepend(icon('ArrowUpRight'));const review=el('button','text-action','Solicitar contacto');review.type='button';review.append(icon('ArrowRight'));bottom.append(human,review);composer.append(bottom);panel.append(composer);
  let config={ready:false,emailReady:false,services:FALLBACK},p={},auth=null,busy=false,opened=false,accepted=false,form=null,step=0,widgets=[],trigger=null,offline=false;
  const storage={get(k){try{return JSON.parse(sessionStorage.getItem('iqx-commercial-'+k));}catch{return null;}},set(k,v){try{sessionStorage.setItem('iqx-commercial-'+k,JSON.stringify(v));}catch{}},remove(k){try{sessionStorage.removeItem('iqx-commercial-'+k);}catch{}}};
  auth=storage.get('session');input.value=storage.get('draft')||'';
  const activeSurface=()=>form||timeline;
  const scroll=()=>requestAnimationFrame(()=>{const surface=form?requestView:timeline;surface.scrollTop=surface.scrollHeight;});
  function message(text,user=false){const n=el('div','message'+(user?' user':''),text),time=el('small','time',new Intl.DateTimeFormat('es-EC',{hour:'2-digit',minute:'2-digit'}).format(new Date()));n.append(time);timeline.append(n);scroll();return n;}
  function answer(reply,question){return message([reply,question].filter(Boolean).join('\n\n'));}
  function clearOptions(){timeline.querySelectorAll('.options,.services').forEach(n=>n.remove());}
  function choices(items){const n=el('div','options');for(const [label,value] of items){const b=el('button','choice',label);b.type='button';b.onclick=()=>{if(busy)return;n.remove();deliver(value);};n.append(b);}timeline.append(n);scroll();}
  const SELECTS={experience:{label:'Años de entrenamiento',placeholder:'Elige tu experiencia',options:['Estoy empezando','Menos de 1 año',...Array.from({length:10},(_,i)=>(i+1)+(i===0?' año':' años')),'Más de 10 años']},modality:{label:'Modalidad preferida',placeholder:'Elige una modalidad',options:['Presencial en Cuenca','Online','Me es indiferente']}};
  function selectOptions(select,key,current=''){
    const spec=SELECTS[key],items=spec?spec.options.map(value=>({value,label:value})):config.services.map(s=>({value:s.id,label:s.name+' · $'+s.price+'/'+s.period}));
    const placeholder=el('option',null,spec?.placeholder||'Elige un servicio');placeholder.value='';placeholder.disabled=key==='service';select.append(placeholder);
    if(current&&spec&&!items.some(item=>item.value===current))items.unshift({value:current,label:current});
    for(const item of items){const option=el('option',null,item.label);option.value=item.value;select.append(option);}select.value=current;
  }
  function questionOptions(question){
    if(!question)return;const key=activeQuestions().find(([key])=>!p[key])?.[0],spec=SELECTS[key];if(!spec)return;
    const box=el('div','options field question-select'),label=el('label',null,spec.label),select=el('select');select.id='chat-'+key;label.htmlFor=select.id;selectOptions(select,key);
    select.onchange=()=>{if(busy||!select.value)return;deliver(select.value);};box.append(label,select);timeline.append(box);scroll();
  }
  function notice(text,error=false){const n=el('div','notice'+(error?' error':'')),copy=el('p',null,text);n.append(copy);activeSurface().append(n);scroll();return n;}
  const fetchJson=async(url,options={})=>{const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth.token}:{}),...options.headers},signal:AbortSignal.timeout(45000)});const value=await r.json();if(!r.ok)throw Object.assign(new Error(value.error||'unavailable'),{code:value.error,status:r.status});return value;};
  function locked(v){busy=v;send.disabled=v;input.disabled=v;reset.disabled=v;review.disabled=v;const back=form?.querySelector('.request-back');if(back)back.disabled=v;timeline.setAttribute('aria-busy',String(v));requestView.setAttribute('aria-busy',String(v));}
  function services(){timeline.querySelectorAll('.services').forEach(n=>n.remove());const list=el('div','services');for(const s of config.services){const b=el('button','service');b.type='button';b.setAttribute('aria-pressed',String(p.service===s.id));b.append(el('strong',null,s.name),el('span',null,'$'+s.price+'/'+s.period),el('small',null,s.description));b.onclick=()=>{if(busy)return;p.service=s.id;showForm();};list.append(b);}timeline.append(list);scroll();}
  function wa(profile=p){const s=config.services.find(x=>x.id===profile.service),text=['Hola Daniel, me interesa '+(s?.name||'recibir orientacion')+'.',profile.name&&'Nombre: '+profile.name,profile.age&&'Edad: '+profile.age,profile.goal&&'Objetivo: '+profile.goal,profile.experience&&'Experiencia: '+profile.experience,profile.modality&&'Modalidad: '+profile.modality,profile.location&&'Ciudad: '+profile.location,profile.contact&&'Contacto: '+profile.contact,profile.schedule&&'Disponibilidad solicitada: '+profile.schedule,s&&'Precio informado: $'+s.price+'/'+s.period+'.','Solicitud pendiente de confirmación con Daniel.'].filter(Boolean).join('\n');return 'https://wa.me/'+PHONE+'?text='+encodeURIComponent(text);}
  let turnstileLoading;
  function loadTurnstile(){if(window.turnstile)return Promise.resolve();if(!turnstileLoading)turnstileLoading=new Promise((resolve,reject)=>{const script=document.createElement('script');let timer;const fail=reason=>{clearTimeout(timer);turnstileLoading=null;script.remove();console.warn('[commercial challenge script]',reason);reject(Object.assign(new Error('challenge_unavailable'),{code:'challenge_unavailable'}));};script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=()=>{clearTimeout(timer);window.turnstile?resolve():fail('not_ready');};script.onerror=()=>fail('load_failed');timer=setTimeout(()=>fail('timeout'),15000);document.head.append(script);});return turnstileLoading;}
  async function challenge(action){
    host.dataset.verification='loading';
    await loadTurnstile();
    // Turnstile necesita un contenedor en el DOM del documento; el slot conserva
    // su posicion en el chat sin encerrar su renderizador en nuestro Shadow DOM.
    const shell=el('div','challenge'),slot=el('slot'),container=el('div');
    slot.name='iqx-commercial-challenge';container.slot=slot.name;container.style.minHeight='65px';container.style.maxWidth='100%';
    shell.append(slot);host.append(container);activeSurface().append(shell);scroll();
    return new Promise((resolve,reject)=>{
      let id,timer,settled=false;
      const finish=(value,error)=>{if(settled)return;settled=true;clearTimeout(timer);if(id!==undefined){try{window.turnstile.remove(id);}catch{}widgets=widgets.filter(x=>x!==id);}container.remove();shell.remove();error?reject(Object.assign(new Error(error),{code:error})):resolve(value);};
      timer=setTimeout(()=>{host.dataset.verification='timeout';finish(null,'challenge_unavailable');},45000);
      try{id=window.turnstile.render(container,{sitekey:config.siteKey,action,theme:'dark',size:'flexible',callback:token=>{host.dataset.verification='complete';finish(token);},'error-callback':code=>{const technical=/^\d+$/.test(String(code))?String(code):'error';host.dataset.verification='sdk-'+technical;console.warn('[commercial challenge]',technical);finish(null,'challenge_unavailable');return true;},'expired-callback':()=>{host.dataset.verification='expired';finish(null,'challenge_required');}});widgets.push(id);}
      catch(error){const technical=Number.isInteger(error?.code)?error.code:'render_failed';host.dataset.verification='render-'+technical;console.warn('[commercial challenge render]',technical);finish(null,'challenge_unavailable');}
    });
  }
  async function init(){timeline.append(el('div','stamp','Hoy'));message('Hola, soy IronQx Assistant.\n¿Buscas una consulta puntual o un acompañamiento mensual?');try{config=await fetchJson(API+'?action=config');}catch{offline=true;}
    if(auth&&config.ready&&auth.expiresAt>Date.now()){try{const h=await fetchJson(API);accepted=true;p=h.profile;for(const turn of h.history){message(turn.message,true);answer(turn.reply,turn.question);}const pending=storage.get('pending');if(pending){if(h.history.some(t=>t.id===pending.id))storage.remove('pending');else{const box=notice('Hay una consulta pendiente de comprobar. No la enviaremos de nuevo automaticamente.'),b=el('button','choice','Comprobar');b.type='button';b.onclick=()=>{box.remove();deliver(pending.text,{id:pending.id});};box.append(b);}}if(h.history.length&&!h.history.at(-1).question&&!h.history.at(-1).humanOnly)services();else questionOptions(h.history.at(-1)?.question);return;}catch{auth=null;storage.remove('session');}}
    choices([['Consulta médica','Busco una consulta médica'],['Plan personalizado','Busco un plan personalizado']]);}
  async function ensureSession(){if(!config.ready||offline)return false;if(auth&&auth.expiresAt>Date.now())return true;
    if(!accepted){const box=notice('Anthropic procesará tu texto y datos básicos para orientarte. Evita compartir historias clínicas o información sensible.');box.classList.add('consent');box.prepend(el('h2','notice-title','Antes de continuar'));box.append(el('p','privacy','La sesión dura 24 horas y los registros se eliminan a los 35 días. Compartir datos con Daniel requiere tu autorización.'));const actions=el('div','consent-actions'),yes=el('button','primary','Aceptar y continuar'),no=el('button','primary secondary','Seguir sin IA');yes.type=no.type='button';actions.append(yes,no);box.append(actions);scroll();await new Promise(resolve=>{yes.onclick=()=>{accepted=true;box.remove();resolve();};no.onclick=()=>{offline=true;box.remove();resolve();};});if(!accepted)return false;}
    const token=await challenge('commercial');auth=await fetchJson(API,{method:'POST',body:JSON.stringify({action:'start',consent:true,turnstileToken:token})});storage.set('session',auth);return true;}
  const questions=[['name','¿Cómo te llamas?'],['age','¿Qué edad tienes?'],['goal','¿Qué te gustaría mejorar o consultar?'],['experience','¿Estás empezando a entrenar, ya entrenas o buscas una consulta puntual?'],['modality','¿Prefieres atención presencial en Cuenca u online?']];
  const activeQuestions=()=>questions.filter(([key])=>!(key==='experience'&&p.service==='consulta'));
  function guided(text){if(step===0&&!p.name&&!p._started){p._started=true;if(/consulta/i.test(text))p.service='consulta';message('Podemos preparar una solicitud para Daniel. Vamos con unos datos básicos.');message(questions[0][1]);return;}
    const q=activeQuestions(),[key]=q[step]||[];
    if(key==='age'){const age=Number(text);if(!Number.isInteger(age)||age<1||age>100){message('Escribe tu edad en años, por favor.');return;}p.age=age;if(age<18){message('Daniel debe revisar tu caso con tu representante. Contactalo directamente; no completaremos una contratacion automatica.');return;}}
    else if(key)p[key]=text.slice(0,key==='name'?80:180);
    step++;if(step<q.length){message(q[step][1]);questionOptions(q[step][1]);return;}message('Estas son las opciones publicadas. Elige una para revisar y editar tu solicitud; Daniel confirma la modalidad y disponibilidad.');services();}
  const errors={session_expired:'La sesión vencio. Puedes empezar de nuevo o continuar directamente con Daniel.',limit_or_busy:'Alcanzamos el limite de consultas o hay una consulta en curso. Puedes continuar con Daniel.',daily_limit:'Llegamos al limite de solicitudes. Puedes hablar directamente con Daniel.',request_uncertain:'No pudimos confirmar la respuesta. Comprobar no genera otra consulta ni otro cobro.',challenge_unavailable:'No se pudo completar la verificacion. Tu mensaje sigue aquí; puedes continuar con Daniel.',challenge_required:'La verificacion vencio. Vuelve a intentarlo.',provider_unavailable:'El asistente no esta disponible en este momento. Tu mensaje no se ha perdido.',not_configured:'El chat IA no esta disponible por ahora. Puedes preparar tu solicitud o hablar con Daniel.'};
  async function deliver(text,retry=null){text=text.trim();if(!text||busy)return;if(!navigator.onLine){notice('Sin conexión. Conservamos tu borrador; no lo enviaremos automáticamente.',true);input.value=text;storage.set('draft',text);return;}
    locked(true);clearOptions();if(!retry)message(text,true);input.value='';input.style.height='';storage.remove('draft');const previous=storage.get('pending'),id=retry?.id||(previous?.text===text?previous.id:crypto.randomUUID());let pending;
    try{if(!await ensureSession()){if(!timeline.querySelector('[data-guided]')){const n=notice('La orientacion IA no esta disponible ahora. Puedes preparar los datos para Daniel sin enviar nada a un modelo.');n.dataset.guided='true';if(!Object.keys(p).length)p={_guided:true};}guided(text);return;}
      pending=el('div','message pending','Un momento...');timeline.append(pending);scroll();storage.set('pending',{id,text});
      const r=await fetchJson(API,{method:'POST',body:JSON.stringify({action:'message',message:text,requestId:id})});p=r.profile;answer(r.reply,r.question);if(r.recommended&&!r.question){services();}else questionOptions(r.question);storage.remove('pending');
    }catch(e){if(e.code==='session_expired'){auth=null;storage.remove('session');}const box=notice(errors[e.code]||'No pudimos completar la consulta. Puedes reintentar o continuar con Daniel.',true),b=el('button','choice',e.code==='request_uncertain'?'Comprobar':'Reintentar');b.type='button';b.onclick=()=>{box.remove();deliver(text,{id:['provider_unavailable','provider_invalid','previous_failed'].includes(e.code)?crypto.randomUUID():id});};box.append(b);input.value=text;storage.set('draft',text);}
    finally{pending?.remove();locked(false);scroll();}}
  function returnToChat(){form?.remove();form=null;requestView.hidden=true;timeline.hidden=false;composer.hidden=false;input.focus({preventScroll:true});}
  function showForm(){if(busy)return;form?.remove();const saved=storage.get('lead');if(saved?.serialized){try{p={...p,...JSON.parse(saved.serialized)};}catch{storage.remove('lead');}}timeline.hidden=true;composer.hidden=true;requestView.hidden=false;form=el('form','lead-form');form.setAttribute('aria-label','Solicitud de contacto');const intro=el('div','request-intro'),title=el('h2','lead-title',p.service==='consulta'?'Tu consulta':'Tu siguiente paso');const back=el('button','text-action request-back','Volver al chat');back.type='button';back.title='Volver al chat';back.setAttribute('aria-label',back.title);back.prepend(icon('ArrowLeft'));back.onclick=()=>{p=values();returnToChat();};intro.append(back,title,el('p','request-description','Revisa tus datos antes de compartirlos con Daniel.'));form.append(intro);
    const fields=el('div','fields'),controls={};
    function field(key,label,type='text',wide=true){const n=el('div','field'+(wide?' wide':'')),l=el('label',null,label),v=el(type==='select'?'select':type==='textarea'?'textarea':'input');v.id='lead-'+key;l.htmlFor=v.id;if(v.tagName==='INPUT')v.type=type;v.required=['name','age','goal','service','contact','schedule'].includes(key);v.maxLength=key==='name'?80:180;if(key==='age'){v.min='18';v.max='100';v.step='1';v.inputMode='numeric';}if(key==='contact')v.autocomplete='email';if(key==='name')v.autocomplete='name';if(type==='select')selectOptions(v,key,p[key]||'');else v.value=p[key]||'';n.append(l,v);fields.append(n);controls[key]=v;}
    function heading(text){const h=el('h3','field-heading',text);fields.append(h);}
    heading('Sobre ti');field('name','Nombre','text',false);field('age','Edad','number',false);field('goal','Objetivo o motivo','textarea');field('experience',SELECTS.experience.label,'select');heading('Tu atención');field('modality',SELECTS.modality.label,'select');field('location','Ciudad');field('service','Servicio','select');heading('Cómo contactarte');field('contact','Tu WhatsApp o correo');field('schedule','Dias y horarios que te convienen');form.append(fields);
    function checkbox(text){const l=el('label','check'),v=el('input');v.type='checkbox';v.required=true;l.append(v,el('span',null,text));form.append(l);return v;}
    const price=checkbox('He revisado el precio del servicio seleccionado. Esta solicitud no confirma una cita ni implica un pago.'),consent=checkbox('Autorizo compartir estos datos con Daniel para responder a mi solicitud.');
    const action=el('div','actions'),email=el('button','primary','Enviar solicitud a Daniel');email.type='submit';email.prepend(icon('Send'));action.append(email);const waButton=el('button','primary secondary','Continuar por WhatsApp');waButton.type='button';waButton.prepend(icon('ArrowUpRight'));action.append(waButton);form.append(action);
    const status=el('div','form-status');status.setAttribute('role','status');form.append(status,el('p','privacy','Solo se comparte el resumen que revisaste, no la conversación. Daniel confirmará disponibilidad.'));
    function values(){return Object.fromEntries(Object.entries(controls).map(([k,v])=>[k,k==='age'?Number(v.value):v.value.trim()]));}
    function validate(){if(!form.reportValidity())return null;const v=values();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.contact)&&!/^\+?[\d ()-]{7,24}$/.test(v.contact)){controls.contact.setCustomValidity('Introduce un correo o numero de WhatsApp valido.');controls.contact.reportValidity();return null;}return v;}
    controls.contact.oninput=()=>controls.contact.setCustomValidity('');controls.service.onchange=()=>{price.checked=false;};
    waButton.onclick=()=>{const value=validate();if(!value)return;p=value;window.open(wa(value),'_blank','noopener,noreferrer');status.textContent='WhatsApp se abre con el resumen. Pulsa enviar allí para entregarselo a Daniel.';};
    let leadRequest=saved||null;
    form.onsubmit=async e=>{e.preventDefault();if(busy)return;const value=validate();if(!value)return;if(!navigator.onLine){status.textContent='Sin conexión. Tus datos siguen aquí; vuelve cuando tengas señal.';return;}if(!config.emailReady){status.textContent='El correo automático no esta disponible ahora. Usa WhatsApp para enviar este mismo resumen.';return;}email.disabled=true;waButton.disabled=true;locked(true);
      try{if(!await ensureSession()){status.textContent='Puedes enviar el resumen por WhatsApp sin utilizar IA.';return;}const serialized=JSON.stringify(value);if(leadRequest&&leadRequest.serialized!==serialized)throw Object.assign(new Error(),{code:'lead_already_submitted'});leadRequest ||= {id:crypto.randomUUID(),serialized};storage.set('lead',leadRequest);const token=await challenge('commercial-lead');const r=await fetchJson(LEAD,{method:'POST',body:JSON.stringify({requestId:leadRequest.id,profile:value,priceAccepted:price.checked,shareConsent:consent.checked,turnstileToken:token})});if(r.sent){status.textContent='Solicitud enviada por correo a Daniel. Tu cita sigue pendiente de confirmación. Tambien puedes continuar por WhatsApp.';email.hidden=true;for(const c of Object.values(controls))c.disabled=true;p=value;}}
      catch(e){status.textContent=e.code==='lead_already_submitted'?'Esta solicitud ya fue procesada. Continua con Daniel por WhatsApp.':e.code==='delivery_uncertain'?'No pudimos confirmar la entrega. Puedes comprobar reintentando sin duplicar el correo, o usar WhatsApp.':errors[e.code]||'No pudimos enviar el correo. Reintenta o envia el resumen por WhatsApp.';}
      finally{email.disabled=false;waButton.disabled=false;locked(false);}};
    requestView.replaceChildren(form);requestView.scrollTop=0;controls.name.focus({preventScroll:true});}
  function fitViewport(){const v=window.visualViewport;host.style.setProperty('--chat-vh',(v?.height||innerHeight)+'px');host.style.setProperty('--chat-vtop',(v?.offsetTop||0)+'px');if(!panel.hidden)fab.hidden=innerWidth<=600;}
  window.visualViewport?.addEventListener('resize',fitViewport);window.visualViewport?.addEventListener('scroll',fitViewport);window.addEventListener('resize',fitViewport);fitViewport();
  let previousOverflow='',inertNodes=[];
  function setOpen(value,source){if(value===!panel.hidden)return;backdrop.hidden=!value;if(value){trigger=source||fab;panel.hidden=false;fab.hidden=innerWidth<=600;fab.setAttribute('aria-expanded','true');previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';inertNodes=[...document.body.children].filter(n=>n!==host&&!n.inert);inertNodes.forEach(n=>n.inert=true);if(!opened){opened=true;init();}requestAnimationFrame(()=>{(form?.querySelector('input')||input).focus({preventScroll:true});});}
    else{panel.hidden=true;fab.hidden=false;fab.setAttribute('aria-expanded','false');document.body.style.overflow=previousOverflow;inertNodes.forEach(n=>n.inert=false);inertNodes=[];trigger?.focus({preventScroll:true});}}
  backdrop.onclick=()=>setOpen(false);
  fab.onclick=()=>setOpen(panel.hidden);close.onclick=()=>setOpen(false);review.onclick=showForm;
  reset.onclick=()=>{if(busy||!confirm('¿Empezar una nueva conversación? No cancela solicitudes ya enviadas.'))return;auth=null;p={};accepted=false;step=0;storage.remove('session');storage.remove('pending');storage.remove('draft');storage.remove('lead');input.value='';returnToChat();timeline.replaceChildren();init();};
  composer.onsubmit=e=>{e.preventDefault();deliver(input.value);};input.oninput=()=>{storage.set('draft',input.value);input.style.height='auto';input.style.height=Math.min(input.scrollHeight,110)+'px';};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();deliver(input.value);}};
  root.addEventListener('keydown',e=>{if(panel.hidden)return;if(e.key==='Escape'){e.preventDefault();setOpen(false);}if(e.key==='Tab'){const nodes=[...panel.querySelectorAll('button,a,input,textarea,select')].filter(n=>!n.disabled&&!n.hidden&&n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&root.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&root.activeElement===last){e.preventDefault();first.focus();}}});
  window.ironqxAssistant={open:source=>setOpen(true,source)};
  document.querySelectorAll('[data-open-assistant]').forEach(n=>n.addEventListener('click',()=>setOpen(true,n)));
})();
